apps_server/dashboard/urls.py
from django.urls import path
from apps_server.dashboard.views import *
#DEFINICION MAS ESPECIFICA
app_name = 'dashboard'
urlpatterns = [
    path('', DeviceListView.as_view(), name='device_list'),
    #DEVICE
    path('device/add/', DeviceCreateView.as_view(), name='device_create'),
    path('device/update/<int:pk>/', CategoryUpdateView.as_view(), name='device_update'),
    path('device/delete/<int:pk>/', DeviceDeleteView.as_view(), name='device_delete'),
    #DATA DEVICE
    path('device/data/', DeviceDataListView.as_view(), name='device_data_list'),
]

login/urls.py
from django.urls import path
from login.views import *
urlpatterns = [
    #path('',LoginFormsView.as_view(),name='login'),
    path('',LoginFormView.as_view(),name='login'),
    #CERRAR SESSION LOGOUT A TRAVES DE LA CLASE LogoutView
    path('logout/',LogoutView.as_view(),name='logout'),
    #CERRAR SESSUIB LOGOUT A TRAVES DE REDIRECT
    #path('logout/',LogoutRedirectView.as_view(),name='logout'),
]

serverIoTLWC/urls.py
from django.contrib import admin
from django.urls import path, include
from apps_server.homepage.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('lwc_api.urls')),
    #LOGIN
    path('login/',include('apps_server.login.urls')),
    #DASHBOARD
    path('dashboard/',include('apps_server.dashboard.urls')),
    #INICIAL
    path('',IndexView.as_view(),name='index'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.username }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard:device_list' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'dashboard:device_list' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'dashboard:device_list' %}" class="brand-link">
        <img src="{% static 'img/logo.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Hades</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'img/user.png' %}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'dashboard:device_list' %}" class="nav-link">
                        <i class="nav-icon fas fa fa-microchip"></i>
                        <p>
                            Dispositivos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'dashboard:device_data_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-database"></i>
                        <p>
                            Datos Dispositivos
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>